name: Discord notify on master

on:
  push:
    branches: ["master"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord webhook
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          REF: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
          URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          MSG: ${{ github.event.head_commit.message }}
        run: |
          # Discord expects JSON. We'll send a simple "content" message.
          payload=$(jq -n \
            --arg repo "$REPO" \
            --arg actor "$ACTOR" \
            --arg ref "$REF" \
            --arg sha "${SHA:0:7}" \
            --arg url "$URL" \
            --arg msg "$MSG" \
            '{content: ("✅ Push to **" + $ref + "** in **" + $repo + "** by **" + $actor + "**\n" + $msg + "\n" + $url + " (`" + $sha + "`)")}')

          curl -sS -H "Content-Type: application/json" -X POST -d "$payload" "$WEBHOOK"
